### ISSUE TITLE
Make callisto-core installable via pip

### ISSUE THREAD

**Issue by aschn** [SexualHealthInnovations/callisto-core#101]
When I ran `pip install git+https://github.com/SexualHealthInnovations/callisto-core.git@release-7.18.16`, the package appears in my virtualenv site-packages as expected. But the directory tree looked like this:

```
site-packages/
    callisto/
        delivery/
            __init__.py
            ...
        evaluation/
            __init__.py
            ...
```

Specifically, `callisto/__init__.py` was missing. Before adding it, `import callisto` failed. After running `touch path/to/site-packages/callisto/__init__.py`, `import callisto` succeeded.

There are several ways to address this issue, but the goal is to be able to run `pip install callisto-core` then `import callisto` successfully.

**Comment by jisantuc** [comment]
Working on this
