### ISSUE TITLE
adding or updating a requirement requires trashing all Travis caches

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#108]
I think I'm the only one who has access to do that, too, which is a pain. Is there a compromise that allows us to force an update of that cache without sacrificing the big impact that requirements caching has on regular test runs? (cc @divergentdave)

**Comment by divergentdave** [comment]
It looks like this is an open bug in tox, see https://bitbucket.org/hpk42/tox/issues/149/. At this point, the obvious options are to drop caching or duplicate the list of dependencies in tox.ini. From the bitbucket comments, someone has written a tox plugin to automatically recreate tox environments when requirements files change, see https://github.com/signalpillar/tox-battery.

**Comment by divergentdave** [comment]
tox-battery won't work, it currently fails on the "-r requirements.txt" line in `requirements-test.txt`. See signalpillar/tox-battery#3. At this point, the best answer other than throwing away caching might be to manually or automatically rewrite tox.ini with the dependencies.

**Comment by kelseyq** [comment]
Thanks for doing the research on this! I think for now I'm going to add a note in the contributing instructions that builds introducing new requirements will fail until I clear the caches and I'll leave this open if the upstream tox situation changes or someone wants to take a crack at rigging something up.
