### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by keisetsu** [SexualHealthInnovations/callisto-core#112]
The [Django coding style docs](https://docs.djangoproject.com/en/1.9/internals/contributing/writing-code/coding-style/) make reference to their .editorconfig, which makes it easy to setup editors if they support it.

Could probably just rip off django's [.editorconfig](https://github.com/django/django/blob/master/.editorconfig).

**Comment by agude** [comment]
Grabbing it from Django should be easy, I'll put in a PR for that in a moment.

**Comment by lynnco** [comment]
closed via https://github.com/SexualHealthInnovations/callisto-core/pull/129
