### ISSUE TITLE
add hacktoberfest label to newbie issues?

### ISSUE THREAD

**Issue by anna-liao** [SexualHealthInnovations/callisto-core#124]
Hello, I'm new to contributing to open source so not sure if this is the best way to make a suggestion.  It seems that some of the issues may be good candidates for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?

**Comment by jtemporal** [comment]
+1

**Comment by kelseyq** [comment]
I added a couple before the month was up--we'll be more ready next year. Thanks for the nudge!
