### ISSUE TITLE
terms and privacy policy 404 errors

### ISSUE THREAD

**Issue by wgwz** [SexualHealthInnovations/callisto-core#133]
- https://demo.callistocampus.org/about/our-policies/#terms-of-service
- https://demo.callistocampus.org/about/our-policies/#privacy-policy

**Comment by kelseyq** [comment]
ah, thanks for the catch!

**Comment by wgwz** [comment]
no prob! wasn't sure this was the right place to report it, looks it was though. :D

**Comment by lynnco** [comment]
both have been resolved ✔️
