### ISSUE TITLE
Make EmailNotification site aware

### ISSUE THREAD

**Issue by lynnco** [SexualHealthInnovations/callisto-core#143]
TODO

- [x] add sites many to many field
- [x] add a default to the many to many field (may be complicated due to: https://code.djangoproject.com/ticket/2750)
- [ ] add sites field to admin
- [x] add `on_site` filter
- [ ] make queries of email notification use the site filter
- [ ] add view functions that pass in the request to the site filter
- [x] create migration
- [x] (?) update validators to be site aware
- [ ] (?) update `render_body` to use site attribute
- [ ] add tests for all these things

**Comment by lynnco** [comment]
all this should happen after https://github.com/SexualHealthInnovations/callisto-core/pull/142 though

**Comment by lynnco** [comment]
`EmailNotification.objects.get` is called in 

- callisto/delivery/matching.py
- callisto/delivery/report_delivery.py
- callisto/delivery/views.py

but I'm not yet sure if any / all of those calls need to be made site aware

**Comment by lynnco** [comment]
Alright so

- callisto/delivery/report_delivery.py
- callisto/delivery/views.py

I can just pass the request down from the view, but

- callisto/delivery/matching.py

is going to need something different

**Comment by kelseyq** [comment]
matching.py will need site-awareness for userdata single-instance as well. not 100% sure on what the approach should be since we call it from the scheduler...may need that SITE_ID env variable in prod too

**Comment by lynnco** [comment]
The ability to use SITE_ID is unfortunately temporary, eventually the only prod app will be multisite-prod and that app can't have SITE_ID set

**Comment by lynnco** [comment]
For matching we'll need to pull the site of the user that was matched on.

**Comment by kelseyq** [comment]
oh oh oh duh! Yeah, I'll be doing that anyway for the user-aware matching. I'm wondering if there's a compromise we can use here for matching.py while I work on that (hoping to get it done next week)

**Comment by lynnco** [comment]
This issue has morphed quite a bit since I originally created it. https://github.com/SexualHealthInnovations/callisto-core/pull/144 is going to give basic site awareness to Email Notification, working entirely off the SITE_ID setting. I'll be creating a new issue for "advanced" site awareness
