### ISSUE TITLE
create an EmailNotification api

### ISSUE THREAD

**Issue by lynnco** [SexualHealthInnovations/callisto-core#147]
I started addressing this in https://github.com/SexualHealthInnovations/callisto-core/pull/144, but realized the was me doing scope creep so I'll be addressing this in its own PR

**Comment by lynnco** [comment]
A lot of this code would be the notification handling that's currently done in https://github.com/SexualHealthInnovations/callisto-core/blob/f0b8ca40d1ce6b6e90130a2b7ac203f2f53660bc/callisto/delivery/report_delivery.py

**Comment by lynnco** [comment]
it pains me to even be bringing this up, but I think Pdf generation belongs in the notification app too?

**Comment by kelseyq** [comment]
conceptually or because of dependencies?

**Comment by lynnco** [comment]
conceptually

**Comment by kelseyq** [comment]
I could see that, although we also use PDF generation in export, so that might make it a little muddier. Would it be easier or harder to move both email and pdf generation in one pull?

**Comment by lynnco** [comment]
harder. I want to move email in https://github.com/SexualHealthInnovations/callisto-core/pull/149 and look at pdf once thats merged

**Comment by kelseyq** [comment]
sounds good to me!
