### ISSUE TITLE
Projectcallisto.org requires CloudFlare Captcha for VPN/TOR

### ISSUE THREAD

**Issue by rorymbyrne** [SexualHealthInnovations/callisto-core#15]
Hey,

Was on your site via VPN and then TOR and noticed that it blocks both due to your use of CloudFlare. 
AFAIK you can actually remove this problem, esp as some victims may seek to use such services for extra privacy:

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

**Comment by kelseyq** [comment]
I've adjusted the settings to allow TOR browsers for both projectcallisto.org and our college sites. This is a great catch, thank you so much!
