### ISSUE TITLE
Adding to many to many relationship before saving produces an IntegrityError

### ISSUE THREAD

**Issue by lynnco** [SexualHealthInnovations/callisto-core#155]
This has to do with these lines https://github.com/SexualHealthInnovations/callisto-core/blob/573db52e22f6f237f730b7134b0360f38182686b/callisto/notification/models.py#L56-L62

Calling `self.sites.add` before `self.save` is resulting in an `IntegrityError` because the many to many relationship is created before the object exists in the database

A strange quirk with this issue, though, is that I can only replicate it in our private repo, and even then only under certain circumstances (eg. cannot replicate in tests, but can replicate in a repl).

The fix is very basic (swapping the order of `self.sites.add` and `self.save`) but I cannot for the life of me produce a failing test case for it :/

**Comment by kelseyq** [comment]
if you swap the order, are the sites persisted to the DB?

**Comment by lynnco** [comment]
Yes, because ManyToManyField's `add` method does its own save. This is hinted at but not explicitly stated in https://docs.djangoproject.com/en/1.10/topics/db/examples/many_to_many/

**Comment by kelseyq** [comment]
ok! sounds like you should go ahead and make the fix, even though regrettably can't cover it with a test?

**Comment by lynnco** [comment]
Yea, the (frustrating small) fix is here https://github.com/SexualHealthInnovations/callisto-core/pull/153/commits/0e155431fcaa65e686e2a073448218e9affc92bb
