### ISSUE TITLE
add tests to cover PDF report generation

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#19]
want to validate the output of the PDF created in https://github.com/SexualHealthInnovations/callisto-core/blob/master/delivery/report_delivery.py

**Comment by kelseyq** [comment]
I've added some tests in #36 that verify that PDFs are actually created, but we need some tests that verify that the PDF reports have the correct content. See here for an example of how this would work: https://github.com/SexualHealthInnovations/callisto-core/blob/master/tests/callistocore/test_delivery.py#L221-L224

**Comment by kelseyq** [comment]
Specifically, we're missing test coverage of multiple choice answers and perpetrator information (formset):
https://codecov.io/gh/SexualHealthInnovations/callisto-core/src/master/callisto/delivery/report_delivery.py

**Comment by lynnco** [comment]
closed via https://github.com/SexualHealthInnovations/callisto-core/pull/119
