### ISSUE TITLE
allow timezone in delivered report timestamp to be set via settings

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#20]

**Comment by ALawley** [comment]
I'd be up for taking a look at this. Do we have somewhere where time zone settings are coming from, or does that have to be built?

**Comment by kelseyq** [comment]
This is where the timezone is hardcoded now:
https://github.com/SexualHealthInnovations/callisto-core/blob/master/callisto/delivery/report_delivery.py#L28

We want to pull the timezone string from Django's settings file, like this:
https://github.com/SexualHealthInnovations/callisto-core/blob/master/callisto/delivery/report_delivery.py#L267

This one will need a unit test. That'll look a lot like this one:
https://github.com/SexualHealthInnovations/callisto-core/blob/master/tests/callistocore/test_delivery.py#L42-L49
But we'll want to verify that a specific timestamp is in the generated PDF. You can use the `override_settings` test decorator to choose a specific timezone https://github.com/SexualHealthInnovations/callisto-core/blob/master/tests/callistocore/test_views.py#L301

I'm realizing that the test might be a little tricky, so feel free to start a WIP (work-in-progress) pull request and ping me if you get stuck. Thanks for taking this on, Anna--we are rolling out to some non-PST schools very soon and this will be extremely helpful!
