### ISSUE TITLE
store matching information encrypted with the assailant hash as the key

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#21]
(inspired by @swenson)
Currently, the information needed to report a match is stored with other system metadata as database rows. The combination of survivor contact information and unique assailant ID is especially sensitive and we want to protect it further. However, match information is delivered to the reporting party immediately upon a match being found, to prevent users from "fishing" for a specific assailant's name with unfounded match entries. Because of this, stored match entries need to be matchable and deliverable without the survivor who originally submitted needing to enter a key at the time a match is found. 

Encrypting the match data with a Callisto admin-provided symmetric key would provide some security, but relies on strong key management and protection. Additionally, the data is still vulnerable to subpoena. We could encrypt the stored match data asymmetrically with the school/reporting authority's public key. We would still need to keep around assailant identifier data in some form to allow for a match, and we are dependent on the school's key management, which isn't under our full control. 

Chris proposed, instead, using the unique assailant ID as a key to encrypt the survivor contact information. When a survivor submits a report to matching, we first encrypt their contact information using the submitted assailant ID as a key. We then use the submitted assailant ID as a key to try to decrypt the existing matching entries. If any decryption attempt is successful, we know that entry was a match, and we can combine the submitted contact information with the decrypted contact information to compile a match report and deliver it safely to the reporting authority.

**Comment by swenson** [comment]
Yes! A few comments:

Using the assailant ID as a key, and having a way to check if the decryption succeeded, would mean that someone who gets a database dump could try to enumerate assailant IDs, just like trying to break a password. It didn't sound like assailant IDs were particularly difficult to guess. I'd recommend if you wanted to go down this route, you should salt and pepper the assailant IDs before using them to generate keys, storing the salt in the database, and treating the pepper as a secret in your system configuration. The benefit to using pepper is that, even if someone got a copy of the entire database, it would be worthless without the pepper.

The scheme I was referring to initially was ID-based encryption (https://en.wikipedia.org/wiki/ID-based_encryption): a way to turn an ID, like an assailant ID, into a public key, which can only be decrypted using a private key. The private key can only be generated by the server (which could be Callisto admin, or could be a school or reporting authority). If the assailant ID is salted, then the school or reporting authority would not be able to decrypt the information without Callisto giving them the salt and assailant ID.

That may be a bit ambitious though, and there aren't ubiquitous libraries that you can just use, off-the-shelf, for such systems.

Generating the key from a salted and peppered assailant ID is probably sufficient for now.

Another recommendation is, whatever algorithm you use for turning the assailant ID into a key, make it very, very slow (e.g., bcrypt with a large salt, scrypt with large parameters). This isn't going to be done a lot, presumably, so it doesn't have to be fast. The slower this operation is, the harder it will be try to guess the right assailant ID.
