### ISSUE TITLE
set up code coverage tool

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#22]
Leaning towards Codecov, but open to others. Want something that integrates with Travis and ideally has branch coverage

**Comment by divergentdave** [comment]
I got codecov working pretty easily. It integrates well with Travis CI, and it does coverage on branches too. See https://codecov.io/gh/divergentdave/callisto-core/branch/codecov (PR to follow after #35, to avoid merge conflicts)
