### ISSUE TITLE
"render_question" method in callisto/delivery/report_delivery.py is too complex

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#28]
Cyclomatic complexity is too high in method render_question. (17)

https://codeclimate.com/github/SexualHealthInnovations/callisto-core/callisto/delivery/report_delivery.py#issue_5769b1b54a3c920001de113f

**Comment by keisetsu** [comment]
This is getting bad diff coverage, I guess because the original tests don't cover this very well? I wanted to make sure the (extensive) changes in this PR are okay before I started adding/modifying tests.
