### ISSUE TITLE
fix PEP8 violations

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#4]

**Comment by kevindaum** [comment]
I'll work on this. I'll start with the `evaluation` app.

**Comment by kevindaum** [comment]
@kelseyq: How do you feel about the 79 characters/line width limit? 

Related: since migration files are usually auto-generated and seem to adhere to PEP8 _other than_ the line length limit, I'm planning to leave those untouched, but I'll work on them if you'd like.

**Comment by kevindaum** [comment]
For example, this is what `evaluation/models.py` looks like after fixing everything including keeping lines under 80 characters wide: 

[models.py.zip](https://github.com/SexualHealthInnovations/callisto-core/files/296540/models.py.zip)

Some of the method signatures get broken up onto multiple lines, which looks a little funky to me but is probably completely normal and readable to someone who regularly follows strict pep8. Likewise with stuff like 

```python
        self._encrypt_eval_row(
            json.dumps(
                self._extract_answers(
                    json.loads(decrypted_text))),
            key=key)
```

(from `EvalRow.add_report_data()`).

**Comment by kelseyq** [comment]
Hey Kevin! Let's leave migration files for now. In our other open source package I'm using a max line length of 119, same as Django does: 
https://github.com/SexualHealthInnovations/django-wizard-builder/blob/master/setup.cfg#L14
Can you use that? I'll be adding those setup & other packaging files in the next couple days. Thanks!

**Comment by kevindaum** [comment]
Whew, 119 seems more reasonable :-) Yeah, that should work, I'll see if I can get a flake8 vim plugin working alongside the python-mode plugin I've been using. I had a terrible time trying to change python-mode's max_line_length last night, so perhaps I'll fare better with flake8.
