### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gpg'` when running tests locally

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#43]
@kevindaum: wanted to get this hammered out somewhere more discoverable than a PR.

Are you still getting the `FileNotFoundError: [Errno 2] No such file or directory: 'gpg'` errors on your machine? I think this may be an OS issue, so it'd be good for us to document how to fix it if so. What OS are you using? If it's Linux or Mac, can you run `which gpg` and let me know the output? I think that `where gpg` should do the same thing on Windows.

**Comment by kevindaum** [comment]
Yes, I'm still getting those errors. Environment:

- Mac OS 10.11.5. 
- python 3.5.1

And the virtualenv has everything installed that's specified in all the requirements files: 

```
bugsnag (2.5.0)
bumpversion (0.5.3)
cffi (1.7.0)
coverage (4.1)
Django (1.9.7)
django-formtools (1.0)
django-polymorphic (0.9.2)
django-ratelimit (0.6.0)
django-wizard-builder (0.0.1)
environ (1.0)
flake8 (2.6.2)
isort (4.2.5)
mccabe (0.5.0)
mock (2.0.0)
pbr (1.10.0)
pep8 (1.7.0)
Pillow (3.2.0)
pip (8.1.2)
pluggy (0.3.1)
psycopg2 (2.6.1)
py (1.4.31)
pycodestyle (2.0.0)
pycparser (2.14)
pyflakes (1.2.3)
PyNaCl (1.0.1)
PyPDF2 (1.26.0)
python-gnupg (0.3.8)
pytz (2016.4)
reportlab (3.3.0)
setuptools (18.2)
six (1.10.0)
tox (2.3.1)
virtualenv (15.0.2)
WebOb (1.6.1)
wheel (0.29.0)
zxcvbn-py3 (1.1)
```

I can recreate the error just by doing this:

```
$ python
Python 3.5.1 (default, Dec  7 2015, 21:59:10)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gnupg
>>> gpg = gnupg.GPG()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin/envs/callisto/lib/python3.5/site-packages/gnupg.py", line 733, in __init__
    p = self._open_subprocess(["--version"])
  File "/Users/kevin/envs/callisto/lib/python3.5/site-packages/gnupg.py", line 786, in _open_subprocess
    startupinfo=si)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gpg'
>>>
```

**Comment by kelseyq** [comment]
What's the output when you run `which gpg` at the command line?

**Comment by kevindaum** [comment]
I get the same result on python 2.7 except the errors look like `OSError: [Errno 2] No such file or directory`. However, I don't have gpg installed on my system:
```
$ which gpg
gpg not found
```
So I guess that's the problem, eh? 
------------------------------------------------------------------------------------------
Wouldn't you know. I installed `gnugp` with homebrew (`brew install gnupg`) and now the tests pass with python 2 and 3:

```
python runtests.py
Creating test database for alias 'default'...
....................** [Bugsnag] No API key configured, couldn't notify
..................................................
----------------------------------------------------------------------
Ran 70 tests in 4.681s

OK
Destroying test database for alias 'default'...
```

So, seems like we need a place to list non-python system requirements and then either point people to something like the "Installing GPG" section of [this page](http://blog.ghostinthemachines.com/2015/03/01/how-to-use-gpg-command-line/) or write those instructions ourselves.

**Comment by kelseyq** [comment]
Yup! I forgot this was a step I had to complete to get this running. Do you want to add those to the contributing instructions, or should I?

**Comment by kelseyq** [comment]
I went ahead and made it a separate ticket, since you've got a couple on your plate already!
