### ISSUE TITLE
Fix issues spotted by pyflakes

### ISSUE THREAD

**Issue by kevindaum** [SexualHealthInnovations/callisto-core#51]
When I first started working on #4, pyflakes was finding some issues. This _may_ no longer be the case since Travis seems to be running pyflakes on everyone's pull requests now... but it probably still is.

**Comment by kelseyq** [comment]
Thoughts on using flake8? I think it includes pyflakes, right?

**Comment by divergentdave** [comment]
I cleaned up the pyflakes issues in #11, in commits 7a0a9e31d996cd6785b524e068b5074a8bd4f439 and b04df9310705b07933ad0fd47e6c0e3cd96eac88. Yes, Travis CI is running pyflakes now, so it should catch any regressions.

Yeah, flake8 is pyflakes+pep8+extra stuff. (cyclomatic complexity, etc.) We can just use that once the style issues are cleaned up.

**Comment by willingc** [comment]
+1 to using any of the tools in the [Python Code Quality Authority](https://github.com/PyCQA) as they are well maintained.

**Comment by kelseyq** [comment]
We're now running flake8 after #76
