### ISSUE TITLE
Store number of PBKDF2 iterations with encrypted reports

### ISSUE THREAD

**Issue by divergentdave** [SexualHealthInnovations/callisto-core#98]
I think the Report model should store the number of iterations passed to PBKDF2 when deriving the key and encrypting it. This would allow changing the KEY_ITERATIONS parameter down the road, to use more key stretching iterations on newly saved reports.

(Also, I'd like to add a comment in test/settings.py that KEY_ITERATIONS = 100 is for testing purposes only, and insufficient for use in production)

**Comment by kelseyq** [comment]
This is a dupe of #70, but the comment in settings.py is an excellent idea.

**Comment by divergentdave** [comment]
Ah, whoops. Sounds good.
